# Change these first
owner: netz0network # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Netz0
    url: https://netz0.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: dark
  cname: netz0.network
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Netz0 Network Status
  introTitle: "Real-Time Network Status and Service Updates for Netz0"
  introMessage: Welcome to the Netz0 Status Page. Stay updated with real-time information on our network and services, including any incidents or maintenance activities. Your connection is our priority.
  navbar:
    - title: Status
      href: /
    - title: Netz0
      href: https://netz0.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
